export const LOADING_ALL_CHARACTERS_SUCCEEDED = 'LOADING_ALL_CHARACTERS_SUCCEEDED';
export const LOADING_CHARACTERS_SUCCEEDED = 'LOADING_CHARACTERS_SUCCEEDED';
export const SEARCH_CHARACTERS = 'SEARCH_CHARACTERS';
